web/router.ex
defmodule Wood.Router do
  use Wood.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Wood do
    pipe_through :browser # Use the default browser stack

    get "/", RoomController, :index
    get "/rooms/new", RoomController, :new
    post "/rooms", RoomController, :create
    get "/rooms/:id", RoomController, :show
    delete "/rooms/:id", RoomController, :delete

    get "/registrations/new", RegistrationController, :new
    post "/registrations", RegistrationController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", Wood do
  #   pipe_through :api
  # end
end

lib/wood/endpoint.ex
defmodule Wood.Endpoint do
  use Phoenix.Endpoint, otp_app: :wood

  socket "/socket", Wood.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :wood, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_wood_key",
    signing_salt: "0sd/Umlj"

  plug Wood.Router
end

lib/wood/repo.ex
defmodule Wood.Repo do
  use Ecto.Repo, otp_app: :wood
end

web/models/message.ex
defmodule Wood.Message do
  use Wood.Web, :model

  schema "messages" do
    field :body, :string
    belongs_to :user, Wood.User
    belongs_to :room, Wood.Room

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:body, :user_id, :room_id])
    |> validate_required([:body, :user_id, :room_id])
  end
end

web/models/registration.ex
defmodule Wood.Registration do
    import Ecto.Changeset, only: [put_change: 3]
    alias Wood.Repo
    def create(changeset) do
      changeset
      |> put_change(:crypted_password, Comeonin.Bcrypt.hashpwsalt(changeset.params["password"]))
      |> Repo.insert
    end
end

web/models/room.ex
defmodule Wood.Room do
  use Wood.Web, :model

  schema "rooms" do
    field :name, :string
    has_many :messages, Wood.Message
    belongs_to :user, Wood.User


  timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :user_id])
    |> validate_required([:name, :user_id])
    |> validate_length(:name, min: 4, max: 16)
  end
end

web/models/session.ex
defmodule Wood.Session do
  alias Wood.Repo
  alias Wood.User

  def login(params) do
    user = Repo.get_by(User, email: String.downcase(params["email"]))
    case authenticate(user, params["password"]) do
      true -> {:ok, user}
      _    -> :error
    end
  end

  defp authenticate(user, password) do
    case user do
      nil -> false
      _   -> Comeonin.Bcrypt.checkpw(password, user.crypted_password)
    end
  end

  def current_user(conn) do
      id = Plug.Conn.get_session(conn, :current_user)
      if id, do: Repo.get(User, id)
  end

  def logged_in?(conn), do: !!current_user(conn)
end

web/models/user.ex
defmodule Wood.User do
  use Wood.Web, :model

  schema "users" do
    field :email, :string
    field :crypted_password, :string
    field :password, :string, virtual: true

    has_many :messages, Wood.Message
    has_many :rooms, Wood.Room

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :password])
    |> validate_required([:email, :password])
    |> unique_constraint(:email)
    |> validate_format(:email, ~r/@/)
    |> validate_length(:password, min: 5)
  end
end

web/controllers/page_controller.ex
defmodule Wood.PageController do
  use Wood.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/registration_controller.ex
defmodule Wood.RegistrationController do
    use Wood.Web, :controller
    alias Wood.User
    def new(conn, _params) do
      changeset = User.changeset(%User{})
      render(conn, %{changeset: changeset})
    end

    def create(conn, %{"user" => user_params}) do
      changeset = User.changeset(%User{}, user_params)

      case Wood.Registration.create(changeset) do
        {:ok, user} ->
          conn
          |> put_session(:current_user, user.id)
          |> put_flash(:info, "Użytkownik stworzony.")
          |> redirect(to: room_path(conn, :index))
        {:error, changeset} ->
          render(conn, "new.html", changeset: changeset)
      end
    end
  end

web/controllers/room_controller.ex
defmodule Wood.RoomController do
  use Wood.Web, :controller
  alias Wood.Repo
  alias Wood.Room
  import Wood.Session, only: [current_user: 1]
  plug Wood.Plugs.Authenticate

  def index(conn, _params) do
    rooms = Repo.all(Room) |> Repo.preload(:user)
    render(conn, "index.html", %{rooms: rooms})
  end

  def show(conn, %{"id" => id}) do
    room = Repo.get!(Room, id)
    query = from m in Wood.Message, where: m.room_id == ^id
    messages = Repo.all(query) |> Repo.preload(:user)

    render(conn, "show.html", %{room: room, messages: messages})
  end

  def new(conn, _params) do
    changeset = Room.changeset(%Room{})
    render(conn, "new.html", %{changeset: changeset})
  end

  def create(conn, %{"room" => room_params}) do
    room_params = Map.put(room_params, "user_id", current_user(conn).id)

    changeset = Room.changeset(%Room{}, room_params)

    case Repo.insert(changeset) do
      {:ok, _room} ->
        conn
        |> put_flash(:info, "Pokój stworzony.")
        |> redirect(to: room_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
end
  def delete(conn, %{"id" => id}) do
    room = Repo.get!(Room, id)
    Repo.delete!(room)
    conn
      |> put_flash(:info, "Pokój usunięty.")
      |> redirect(to: room_path(conn, :index))
  end
end

web/controllers/session_controller.ex
defmodule  Wood.SessionController do
  use Wood.Web, :controller
  def new(conn, _params) do
    render(conn, "new.html")
  end
  def create(conn, %{"session" => session_params}) do
    case Wood.Session.login(session_params) do
      {:ok, user} ->
        conn
        |> put_session(:current_user, user.id)
        |> put_flash(:info, "Zalogowano")
        |> redirect(to: "/rooms")
      false ->
        conn
        |> put_flash(:info, "Błędne dane")
        |> render("new.html")
      end
  end
  def delete(conn,_params) do
      conn
      |> delete_session(:current_user)
      |> put_flash(:info, "Wylogowano")
      |> redirect(to: room_path(conn, :index))
  end
end

web/views/error_view.ex
defmodule Wood.ErrorView do
  use Wood.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Wood.LayoutView do
  use Wood.Web, :view
end

web/views/page_view.ex
defmodule Wood.PageView do
  use Wood.Web, :view
end

web/views/registration_view.ex
defmodule Wood.RegistrationView do
  use Wood.Web, :view
end

web/views/room_view.ex
defmodule Wood.RoomView do
  use Wood.Web, :view
end

web/views/session_view.ex
defmodule Wood.SessionView do
  use Wood.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Wood vol1.0</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
              <%= if logged_in?(@conn) do %>
                <li id="current-user"><%= current_user(@conn).email %></li>
                <li><%= link "Logout", to: session_path(@conn, :delete), method: :delete %></li>
              <% else %>
                <li><%= link "Login",    to: "/login" %></li>
                <li><%= link "Register", to: registration_path(@conn, :new) %></li>
              <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/room/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Stwórz", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/room/index.html.eex
<h1>Roomz</h1>
<h2>Listing rooms</h2>

<table class="table">
  <thead>
    <tr>
      <th>Nazwa</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for room <- @rooms do %>
    <tr>
      <td><%= room.name %></td>

      <td class="text-right">
        <%= link "Wejdź", to: room_path(@conn, :show, room), class: "btn btn-default btn-xs" %>
        <%= if current_user(@conn) == room.user do %>
        <%= link "Usuń", to: room_path(@conn, :delete, room), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
        <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "nowy pokój", to: room_path(@conn, :new) %>

web/templates/room/new.html.eex
<h2>New room</h2>

<%= render "form.html", changeset: @changeset,
                        action: room_path(@conn, :create) %>

<%= link "Wstecz", to: room_path(@conn, :index) %>

web/templates/room/show.html.eex
<h1 id="room-name"><%= @room.name %></h1>
<div id="room-id"><%= @room.id %></div>

<div class='row form-group'>
  <div class='col-md-12'>
    <div id="chat-box" class="container">
      <%= for  message <- @messages do %>
      <br/> [<%= message.user.email %>]: <%= message.body %>
      <% end %>
      </div>
    <input id="chat-input" class="form-control" placeholder="Message"/>
    <%= link "wyjdź", to: room_path(@conn, :index)%>
  </div>
</div>

web/templates/session/new.html.eex
<h2>Login</h2>

<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
  <div class="form-group">
    <label>Email</label>
    <%= text_input f, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Password</label>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Login", class: "btn btn-primary" %>
  </div>
<% end %>